version: '3'
services:
  mysql:
    container_name: core_mysql
    image: mysql:5.7
    environment:
      TZ: "Europe/Moscow"
      MYSQL_DATABASE: core
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-ptoor"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql_volume:/var/lib/mysql:cached
      - ./mysql/my.custom.cnf:/etc/mysql/conf.d/my.custom.cnf:cached
    networks:
      - default

  redis:
    container_name: core_redis
    image: bitnami/redis:latest
    networks:
      - default
    environment:
      TZ: "Europe/Moscow"
      REDIS_PASSWORD: toor
    expose:
      - "6379"
    ports:
      - "6378:6379"
    volumes:
      - redis_volume:/bitnami:cached

  phpmyadmin:
    container_name: core_phpmyadmin
    image: phpmyadmin/phpmyadmin
    networks:
      - default
    environment:
      TZ: "Europe/Moscow"
      PMA_HOST: mysql
    links:
      - mysql
    expose:
      - 80
    networks:
      - default

  nginx:
    container_name: core_nginx
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/testsite.conf:/etc/nginx/conf.d/testsite.conf
      - ./logs:/logs:cached
      - sock_volume:/var/run
    depends_on:
      - php
    networks:
      - default

  php:
    container_name: core_php
    image: merorafael/php:7.1-fpm
    environment:
      TZ: "Europe/Moscow"
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini:cached
      - ./php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:cached
      - sock_volume:/var/run
    #command: bash -c "bash init.sh --env=docker && php-fpm"
    #restart: on-failure
    depends_on:
      - mysql
      - redis
    networks:
      - default

volumes:
  mysql_volume: {}
  redis_volume: {}
  sock_volume: {}

networks:
  main_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16