<?php
/**
 * Created by PhpStorm.
 * User: artemshmanovsky
 * Date: 15.04.16
 * Time: 21:12
 */

namespace frontend\widgets;


use common\models\Comment;
use common\models\SubscriptionComment;
use frontend\assets\CommentAsset;
use Yii;
use yii\base\Widget;

class CommentsForm extends Widget
{
    public $model_class;
    public $model_id;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function registerClientScript()
    {
        CommentAsset::register($this->getView());
    }

    public function run()
    {
        $this->registerClientScript();

        $model = new Comment();
        $model->model = $this->model_class;
        $model->model_id = $this->model_id;
        $model->parent_id = 0;
        $model->reply_id = 0;
        //$model->deleted = 0;

        $dataProvider = $model->search(Yii::$app->request->post());

        $subscription = new SubscriptionComment();

        if(!Yii::$app->user->isGuest)
            $subscription = SubscriptionComment::find()->where([
                'user_id' => Yii::$app->user->id,
                'model' => $this->model_class,
                'model_id' => $this->model_id,
            ])->one();

        return $this->render('commentsForm', [
            'dataProvider' => $dataProvider,
            'model' => $model,
            'subscription' => $subscription,
            'model_class' => $this->model_class,
            'model_id' => $this->model_id,
        ]);
    }
}